### ISSUE TITLE
Automate templating of package name

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-component-provider-go-boilerplate#8] opened 2021-12-20 15:25 UTC
There's numerous places where we ask the user to replace `xyz` with the name of the module. It would be nicer if we could automate this for the user via a Makefile target or similar mechanism.

Here's what I'm thinking for a solution:

* For source files, use a templating tool (propose [Gomplate](https://docs.gomplate.ca/), and rename the affected source files `filename.ext.tmpl`.
* For directories, rename using shell commands.
* Execute all changes via `make init`.

If we like this, I'm happy to submit a PR.

**Comment by lukehoban** [comment] 2021-12-20 15:44
FWIW - there is a `make prepare` target in the bridge boilerplate - which serves largely this same purpose. Ideally we keep all our boilerplate repos aligned on things like this (either by porting that to the other repos, or by designing something new and ensuring it is pushed to all boilerplate repos).

**Comment by jkodroff** [comment] 2021-12-22 14:40
@lukehoban Yes, that would be the end state - that all boilerplate repos have templating and use the same tooling.  The TF provider boilerplate uses sed, but I think a more modern template engine would be more maintainable.

**Comment by mjeffryes** [comment] 2024-12-16 23:51
closing due to https://github.com/pulumi/pulumi-component-provider-go-boilerplate/issues/34

**Closed as completed by mjeffryes** 2024-12-16 23:51 UTC
Labels: resolution/wont-fix, kind/enhancement
